plank:
  job_url_prefix_config:
    "*": http://35.244.234.234/view/gcs/ # TODO update domain name; change to HTTPS
  pod_pending_timeout: 60m
  default_decoration_config:
    timeout: 7200000000000 # 2h
    grace_period: 15000000000 # 15s
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190311-a967141"
      initupload: "gcr.io/k8s-prow/initupload:v20190311-a967141"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190311-a967141"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190311-a967141"
    gcs_configuration:
      bucket: "prow-test-cxing-gke-dev"
      path_strategy: "legacy"
      default_org: "verult-prowbot"
      default_repo: "Cirq"
    gcs_credentials_secret: "service-account"

    
sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 5m


deck:
  spyglass:
    size_limit: 500000000 # 500MB
    #gcs_browser_prefix: https://gcsweb.k8s.io/gcs/
    #testgrid_config: gs://k8s-testgrid/config
    #testgrid_root: https://testgrid.k8s.io/
    viewers:
      "started.json|finished.json":
      - "metadata"
      "build-log.txt":
      - "buildlog"
      #"artifacts/junit.*\\.xml":
      #- "junit"
  tide_update_period: 1s


presubmits:
  verult-prowbot/Cirq:
  - name: prow-checkconfig
    branches:
    - master
    decorate: true
    run_if_changed: '^prow/'
    skip_report: false
    spec:
      containers:
      - image: gcr.io/k8s-prow/checkconfig:latest
        imagePullPolicy: Always
        command:
        - /checkconfig
        args:
        - --config-path=./prow/config.yaml
        #- --job-config-path=./prow/prowjobs
        - --plugin-config=./prow/plugins.yaml
  - name: mypy
    decorate: true
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: python:3.5.2
        command: ["/bin/sh", "-c"]
        args:
        - pip install --upgrade pip setuptools wheel;
          cat dev_tools/conf/pip-list-dev-tools.txt | grep mypy | xargs pip install;
          check/mypy
  # TODO uncomment after test is fixed
  # - name: pylint
  #   decorate: true
  #   always_run: true
  #   skip_report: false
  #   spec:
  #     containers:
  #     - image: python:3.5.2
  #       command: ["/bin/sh", "-c"]
  #       args:
  #       - pip install --upgrade pip setuptools wheel;
  #         cat dev_tools/conf/pip-list-dev-tools.txt | grep "pylint\|astroid" | grep -v "#" | xargs pip install;
  #         check/pylint
  - name: format
    decorate: true
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: python:3.5.2
        command: ["/bin/sh", "-c"]
        args:
        - pip install --upgrade pip setuptools wheel;
          cat dev_tools/conf/pip-list-dev-tools.txt | grep yapf | xargs pip install;
          check/format-incremental
  # TODO uncomment after test is fixed
  # - name: pytest-and-incremental-coverage
  #   decorate: true
  #   always_run: true
  #   skip_report: false
  #   spec:
  #     containers:
  #     - image: python:3.5.2
  #       command: ["/bin/sh", "-c"]
  #       args:
  #       - pip install --upgrade pip setuptools wheel;
  #         pip install -r requirements.txt;
  #         pip install -r cirq/contrib/contrib-requirements.txt;
  #         pip install -r dev_tools/conf/pip-list-dev-tools.txt;
  #         check/pytest-and-incremental-coverage master
  # TODO uncomment after test is fixed
  # - name: pytest-without-contrib
  #   decorate: true
  #   always_run: true
  #   skip_report: false
  #   spec:
  #     containers:
  #     - image: python:3.6
  #       command: ["/bin/sh", "-c"]
  #       args:
  #       - pip install --upgrade pip setuptools wheel;
  #         pip install -r requirements.txt;
  #         pip install -r dev_tools/conf/pip-list-dev-tools.txt;
  #         check/pytest --ignore=cirq/contrib


postsubmits:
  verult-prowbot/Cirq:
  - name: prow-branchprotector
    decorate: true
    run_if_changed: '^prow/config.yaml$'
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/k8s-prow/branchprotector:latest
        imagePullPolicy: Always
        command:
        - /branchprotector
        args:
        - --config-path=./prow/config.yaml
        - --github-token-path=/etc/oauth-token
        - --confirm
        volumeMounts:
        - name: oauth-token
          mountPath: "/etc/oauth-token"
          readOnly: true
      volumes:
      - name: oauth-token
        secret:
          secretName: oauth-token


branch-protection:
  orgs:
    verult-prowbot:
      repos:
        Cirq:
          branches:
            master:
              protect: true
          # TODO uncomment
          # required_status_checks:
          #   contexts:
          #   - "Travis CI - Pull Request"
          #   - cla/google

            
tide:
  merge_method:
    verult-prowbot/Cirq: squash

  target_url: http://35.244.234.234/tide #TODO https, domain name

  queries:
  - repos:
    - verult-prowbot/Cirq
    labels:
    - automerge
    # TODO uncomment CLA stuff
    #- "cla: yes" 
    #missingLabels:
    #- "cla: no"
    reviewApprovedRequired: true

  context_options:
    # Use branch protection options to define required and optional contexts
    from-branch-protection: true
    # Treat unknown contexts as optional
    skip-unknown-contexts: true

    # Presubmits are automatically recognized by tide as prereqs for merging.
